flags: {}
packages:
- '.'
- location:
    git: 'https://github.com/sivertb/wayland-wire'
    commit: '1c7771360405cf518cdf30d6e62b879cd714988e'
  extra-dep: true
- location:
    git: 'https://github.com/sivertb/diet-set'
    commit: '968ed04294df76450bbaffa693a448edaf47b1a4'
  extra-dep: true
resolver: lts-6.31
extra-deps:
    - diet-set-0.1.0
    - wayland-wire-0.1.0
